* -----------------------------------------------------
* XLS2GMS 2.8      Jul  4, 2010 23.5.1 WIN 18414.18495 VS8 x86/MS Windows       
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Users\Packardbell\Documents\gamsdir\projdir\nonogram.xls
* Sheet:       rows
* Range:       $A$2:$A$30
* -----------------------------------------------------
r1  
r2  
r3  
r4  
r5  
r6  
r7  
r8  
r9  
r10 
r11 
r12 
r13 
r14 
r15 
r16 
r17 
r18 
r19 
r20 
    
    
    
    
    
    
    
    
    
* -----------------------------------------------------
