* -----------------------------------------------------
* XLS2GMS 2.8      Jul  4, 2010 23.5.1 WIN 18414.18495 VS8 x86/MS Windows       
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Users\Packardbell\Documents\gamsdir\projdir\nonogram.xls
* Sheet:       columns
* Range:       $A$2:$A$30
* -----------------------------------------------------
c1  
c2  
c3  
c4  
c5  
c6  
c7  
c8  
c9  
c10 
c11 
c12 
c13 
c14 
c15 
c16 
c17 
c18 
c19 
c20 
    
    
    
    
    
    
    
    
    
* -----------------------------------------------------
