* -----------------------------------------------------
* XLS2GMS 2.8      Jul  4, 2010 23.5.1 WIN 18414.18495 VS8 x86/MS Windows       
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Users\Packardbell\Documents\gamsdir\projdir\nonogram.xls
* Sheet:       shapes
* Range:       $A$1:$A$8
* -----------------------------------------------------
s1  
s2  
s3  
s4  
s5  
s6  
    
    
* -----------------------------------------------------
