* -----------------------------------------------------
* XLS2GMS 2.8      Jul  4, 2010 23.5.1 WIN 18414.18495 VS8 x86/MS Windows       
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Users\Packardbell\Documents\gamsdir\projdir\nonogram.xls
* Sheet:       rows
* Range:       $A$1:$K$30
* -----------------------------------------------------
     s1   s2   s3   s4   s5   s6      
r1   4                                
r2   1    1    1                      
r3   2    1    4    1                 
r4   1    1    1    1    1            
r5   3    1    1    1    1            
r6   1    1    1    1    1            
r7   3    1    1    1                 
r8   1    1    1                      
r9   1    10                          
r10  1    2    6    2                 
r11  1    1    3    3    1            
r12  1    4    4                      
r13  1    4    4                      
r14  3    5    5                      
r15  2    2    5    5                 
r16  3    1    4    4                 
r17  5    4    4                      
r18  3    1    2    2    1            
r19  2    6    2                      
r20  8    10                          
                                      
                                      
                                      
                                      
                                      
                                      
                                      
                                      
                                      
* -----------------------------------------------------
