* -----------------------------------------------------
* XLS2GMS 2.8      Jul  4, 2010 23.5.1 WIN 18414.18495 VS8 x86/MS Windows       
* Erwin Kalvelagen, GAMS Development Corp.
* -----------------------------------------------------
* Application: Microsoft Excel
* Version:     15.0
* Workbook:    C:\Users\Packardbell\Documents\gamsdir\projdir\nonogram.xls
* Sheet:       columns
* Range:       $A$1:$K$30
* -----------------------------------------------------
     s1   s2   s3   s4   s5   s6      
c1   3    1                           
c2   5    1                           
c3   13   3    1                      
c4   1    1    1    2    2    1       
c5   1    1    3    1                 
c6   1                                
c7   1                                
c8   1                                
c9   10                               
c10  2    6    2                      
c11  4    1    8    1                 
c12  1    1    12                     
c13  1    4    3    2    2            
c14  1    1    2    2                 
c15  1    1    2    2                 
c16  1    9    2    2                 
c17  1    12                          
c18  7    8    1                      
c19  2    6    2                      
c20  10                               
                                      
                                      
                                      
                                      
                                      
                                      
                                      
                                      
                                      
* -----------------------------------------------------
